import torch

In [15]:
a= torch.tensor(5)
b=torch.tensor(8)
a*b

tensor(40)

In [19]:
c=torch.tensor([1.,2,3,4])

In [20]:
d=torch.tensor([2,5,8,9])
c*d

tensor([ 2., 10., 24., 36.])

In [11]:
a1=torch.tensor([[[3],[5],[8],[9]]])

In [13]:
a1.shape

torch.Size([1, 4, 1])

In [25]:
x=np.array([[2,3],[5,6]])
y=np.array([[7,8],[3,6]])

In [30]:
y=torch.from_numpy(x)

In [31]:
y

tensor([[2, 3],
        [5, 6]], dtype=torch.int32)

In [32]:
x.dtype

dtype('int32')

In [33]:
y.dtype

torch.int32

Linear Regression

In [71]:
inputs = np.array([[71,82,69],[37,54,76],[45,59,97],[83,28,49]],dtype='float64')
targets = np.array([[78,69],[98,87],[79,96],[58,78]],dtype='float32')
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[71., 82., 69.],
        [37., 54., 76.],
        [45., 59., 97.],
        [83., 28., 49.]], dtype=torch.float64)
tensor([[78., 69.],
        [98., 87.],
        [79., 96.],
        [58., 78.]])


tensor([[71., 82., 69.],
        [37., 54., 76.],
        [45., 59., 97.],
        [83., 28., 49.]], dtype=torch.float64)
tensor([[78., 69.],
        [98., 87.],
        [79., 96.],
        [58., 78.]])
